-- Restricciones NOT NULL e IDENTITY
ALTER TABLE "Administrador"
    ALTER COLUMN "Identificador" SET NOT NULL;

ALTER TABLE "Administrador"
    ALTER COLUMN "Identificador" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Administrador"
    ALTER COLUMN "Usuario" SET NOT NULL;

ALTER TABLE "Administrador"
    ALTER COLUMN "Contrasena" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "Identificador" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "Identificador" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Animal"
    ALTER COLUMN "Nombre" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "Raza" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "Edad" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "Sexo" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "FechaIngreso" SET NOT NULL;

ALTER TABLE "Animal"
    ALTER COLUMN "TipoAnimal" SET NOT NULL;

ALTER TABLE "Administrador"
    ADD CONSTRAINT "Administrador_Usuario_Maximo15"
    CHECK (char_length("Usuario") <= 15);

ALTER TABLE "Administrador"
    ADD CONSTRAINT "Administrador_Contrasena_Maximo60"
    CHECK (char_length("Contrasena") <= 60);

ALTER TABLE "Animal"
    ADD CONSTRAINT "Animal_Sexo_ValoresPermitidos"
    CHECK ("Sexo" IN ('Hembra', 'Macho'));

ALTER TABLE "Animal"
    ADD CONSTRAINT "Animal_TipoAnimal_ValoresPermitidos"
    CHECK ("TipoAnimal" IN ('Perro', 'Gato'));

ALTER TABLE "Animal"
    ADD CONSTRAINT "Animal_Edad_NoNegativa"
    CHECK ("Edad" >= 0);

-- Restricciones PRIMARY KEY y UNIQUE
ALTER TABLE "Administrador"
    ADD CONSTRAINT "Administrador_PK" PRIMARY KEY ("Identificador");

ALTER TABLE "Administrador"
    ADD CONSTRAINT "Administrador_Usuario_UNIQUE" UNIQUE ("Usuario");

ALTER TABLE "Animal"
    ADD CONSTRAINT "Animal_PK" PRIMARY KEY ("Identificador");

-- Restricciones DEFAULT
ALTER TABLE "Animal"
    ALTER COLUMN "FechaIngreso" SET DEFAULT CURRENT_DATE;
